services:
  front:
    build:
      context: ./
      args:
        MODE: development
      dockerfile: Dockerfile.front.development
    image: develeens/callpro_app_front:1.0.0
    container_name: callpro_app_front
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--no-warnings=ExperimentalWarning
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    ports:
      - "8081:3001"
    volumes:
    - callpro_app_front_node_modules:/app/node_modules
    - ./:/app
volumes:
  callpro_app_front_node_modules: