name: CI/CD for Test Environment

on:
  push:
    branches:
      - develop

jobs:
  build_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup pnpm
        run: corepack enable

      - name: Install dependencies and build
        env:
          NUXT_ENV: test
          NUXT_PUBLIC_TEST_URL: http://devp.thecallpro.com/api
        run: |
          pnpm install --frozen-lockfile
          pnpm generate -o .output/public

      - name: Include firebase.json in build artifacts
        run: |
          echo "Ensuring firebase.json is included in build artifacts"
          cp firebase.json .output/public/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-output
          path: .output/public

  deploy_to_test:
    runs-on: ubuntu-latest
    needs: build_develop
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-output

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Debugging List downloaded files
        run: |
          echo "Current directory:"
          pwd
          echo "Downloaded files:"
          ls -la

      - name: Move artifacts to .output/public
        run: |
          mkdir -p .output/public
          mv * .output/public || echo "No files to move"

      - name: Deploy to Firebase Hosting
        run: |
          echo "Deploying from directory $(pwd)"
          firebase deploy --project the-callpro-system --only hosting:test-thecallproportal
