name: CI/CD for Test Environment

on:
  push:
    branches:
      - develop

jobs:
  build_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup pnpm
        run: corepack enable

      - name: Install dependencies and build
        env:
          NUXT_ENV: test
          NUXT_PUBLIC_TEST_URL: http://devp.thecallpro.com/api
        run: |
          pnpm install --frozen-lockfile
          pnpm generate -o .output/public

      - name: Debug build artifacts
        run: |
          echo "Listing .output directory:"
          ls -la .output
          echo "Listing public directory:"
          ls -la .output/public

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-output
          path: .output/public

  deploy_to_test:
    runs-on: ubuntu-latest
    needs: build_develop
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-output

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Move build to root directory
        run: |
          echo "Moving build artifacts to root directory"
          mv nuxt-output/* .

      - name: Debugging Verify files in root
        run: |
          echo "Current directory:"
          pwd
          echo "Root files:"
          ls -la
          echo "Public directory:"
          ls -la public || echo "Public directory missing"

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ ! -f firebase.json ]; then
            echo "Error: firebase.json not found!"
            exit 1
          fi
          firebase deploy --only hosting:test-thecallproportal --token ${{ secrets.FIREBASE_TOKEN }}
