name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Firebase
        uses: firebase/action-gcp-auth@v0
        with:
          project_id: the-callpro-system
      - name: Install dependencies
        run: npm install
      - name: Build Nuxt app
        env: 
          NUXT_ENV: test
          NUXT_PUBLIC_TEST_URL: http://devp.thecallpro.com/api
        run: npm run generate
      - name: Deploy to Firebase Hosting
        uses: firebase/action-hosting-deploy@v0
        with:
          project: the-callpro-system
          site: test-thecallproportal 
          source: .output/public