name: CI/CD for Test Environment

on:
  push:
    branches:
      - develop

jobs:
  build_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup pnpm
        run: corepack enable

      - name: Install dependencies and build
        env:
          NUXT_ENV: test
          NUXT_PUBLIC_TEST_URL: http://devp.thecallpro.com/api
        run: |
          pnpm install --frozen-lockfile
          pnpm generate -o .output/public
      - name: Debug build artifacts
        run: |
          echo "Listing .output directory:"
          ls -la .output
          echo "Listing public directory:"
          ls -la .output/public
      - name: Copy firebase.json to build directory
        run: |
          echo "Ensuring firebase.json is included in the build artifacts."
          cp firebase.json .output/public/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuxt-output
          path: .output/public

  deploy_to_test:
    runs-on: ubuntu-latest
    needs: build_develop
    steps:
      - name: Setup pnpm
        run: corepack enable

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: nuxt-output

      - name: Login to Firebase
        uses: firebase/action-gcp-auth@v0
        with:
          project_id: the-callpro-system

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Debugging Verify downloaded artifacts
        run: |
          echo "Listing downloaded artifacts:"
          ls -la
      - name: Deploy to Firebase Hosting
        run: |
          echo "Deploying from directory $(pwd)"
          firebase deploy --project the-callpro-system --only hosting:test-thecallproportal